# Generated by Django 3.2.6 on 2021-09-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tipocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(default='', max_length=20),
        ),
    ]
