# Generated by Django 3.2.6 on 2021-09-16 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=200)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('nombre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.estudiante')),
            ],
        ),
    ]
